AWSTemplateFormatVersion: '2010-09-09'
Description: Send custom security findings to AWS Security Hub

# Reference - https://github.com/aws-samples/aws-securityhub-remediations/blob/main/aws-ecr-continuouscompliance/

Parameters:
  BucketPrefix:
    Type: String
    Description: Lambda source code limited to 4096 characters
  BucketKey:
    Type: String
    Description: Lambda source code limited to 4096 characters

Resources:
  CaptureECRImageScanEvents:
    Type: AWS::Events::Rule
    Properties:
      Description: Capture ECR scan event and trigger action
      EventPattern:
        source:
          - aws.ecr
        detail-type:
          - ECR Image Scan
      Name: CaptureECRScanEvent
      State: ENABLED
      Targets:
        - Arn: !GetAtt CustomSecurityFindingsLambda.Arn
          Id: IDCustomSecurityFindingsEvents

  CaptureIAMUserCreationEvents:
    Type: AWS::Events::Rule
    Properties:
      Description: Capture new IAM user creation event and trigger action
      EventPattern:
        source:
          - aws.iam
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - iam.amazonaws.com
          eventName:
            - CreateUser
      Name: CaptureIAMUserCreationEvent
      State: ENABLED
      Targets:
        - Arn: !GetAtt CustomSecurityFindingsLambda.Arn
          Id: IDCustomSecurityFindingsEvents

  CustomSecurityFindingsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CustomSecurityFindingsLambda
      Description: Maps custom security findings into ASFF before importing to Security Hub
      Handler: index.lambda_handler
      MemorySize: 384
      Role: !GetAtt CustomSecurityFindingsLambdaRole.Arn
      Runtime: python3.7
      Timeout: 70
      Environment:
        Variables:
          account_num: !Ref 'AWS::AccountId'
          region: !Ref 'AWS::Region'
      Code:
        S3Bucket: !Sub '${BucketPrefix}-${AWS::Region}'
        S3Key: !Ref BucketKey
      Tags:
        - Key: DO_NOT_DELETE
          Value: True

  CustomSecurityFindingsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: CustomSecurityFindingsLambda-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - securityhub:BatchImportFindings
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action:
              - sts:AssumeRole
      Tags:
        - Key: DO_NOT_DELETE
          Value: True

  PermissionForECREventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CustomSecurityFindingsLambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt "CaptureECRImageScanEvents.Arn"

  PermissionForIAMEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CustomSecurityFindingsLambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt "CaptureIAMUserCreationEvents.Arn"
